version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default port for RabbitMQ
      - "15672:15672" # Default port for RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Default port for MongoDB
    volumes:
      - mongodb_data:/data/db # Persistent storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    ports:
      - "1433:1433" # Default port for MS SQL Server
    environment:
      ACCEPT_EULA: "Y" # Required to accept the license agreement
      SA_PASSWORD: "YourStrongPassword123" # Set a strong password for the 'sa' user
    volumes:
      - mssql_data:/var/opt/mssql # Persistent storage

volumes:
  mongodb_data:
  mssql_data: